# Model arguments
model_name_or_path: herman66/Qwen2.5-0.5B-Open-R1-Distill #这是我SFT的结果，如果你直接执行可以直接使用这个值，如果你SFT已经执行完毕，请修改为自己的名称
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: AI-MO/NuminaMath-TIR
dataset_configs:
- all
num_processes: 0

# GRPO trainer config
bf16: true
use_vllm: false
vllm_device: auto
vllm_gpu_memory_utilization: 0.3
do_eval: true
eval_strategy: steps
eval_steps: 100
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-0.5B-Open-R1-GRPO
hub_strategy: every_save
learning_rate: 5e-6
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 200
max_steps: -1
num_generations: 2
num_train_epochs: 1
output_dir: data/Qwen2.5-0.5B-Open-R1-GRPO
overwrite_output_dir: true
per_device_eval_batch_size: 2  # 修改为 2
per_device_train_batch_size: 2
save_steps: 35
max_grad_norm: 0.1
push_to_hub: true
report_to:
- wandb
save_strategy: "no"
seed: 42
warmup_ratio: 0.1